# Generated by Django 5.0.7 on 2024-08-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postalAddress',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoneCode',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
