# Generated by Django 5.0.7 on 2024-08-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_postaladdress_customuser_zonecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='postalAddress',
            new_name='postal_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='zoneCode',
            new_name='zone_code',
        ),
    ]
