# Generated by Django 5.0.7 on 2024-07-19 08:06

import django.db.models.deletion
import rememberTree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembertree',
            name='flowerType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='remembertree',
            name='myName',
            field=models.CharField(default='토닥토닥', max_length=100),
        ),
        migrations.AlterField(
            model_name='remembertree',
            name='treeName',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rememberPhoto', models.ImageField(upload_to=rememberTree.models.user_photo_upload_to)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rememberDate', models.DateField(default='2024-07-19')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remember_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rememberTree.remembertree')),
            ],
        ),
    ]
