# Generated by Django 5.0.7 on 2024-07-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='content',
            field=models.TextField(max_length=790),
        ),
    ]
