# Generated by Django 5.0.7 on 2024-07-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0002_alter_letters_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='rememberDate',
        ),
        migrations.AddField(
            model_name='photo',
            name='subComment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
