# Generated by Django 5.0.7 on 2024-07-19 03:14

import django.db.models.deletion
import rememberTree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0002_alter_remembertree_flowertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rememberTree.models.user_photo_upload_to)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remember_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rememberTree.remembertree')),
            ],
        ),
    ]
