# Generated by Django 5.0.7 on 2024-07-30 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0003_remove_photo_rememberdate_photo_subcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='subComment',
        ),
        migrations.AddField(
            model_name='photo',
            name='rememberDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='letters',
            name='content',
            field=models.TextField(max_length=780),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
