# Generated by Django 5.0.7 on 2024-07-19 08:41

import datetime
import rememberTree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0003_alter_photo_comment_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='rememberDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='rememberPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=rememberTree.models.user_photo_upload_to),
        ),
    ]
