# Generated by Django 5.0.7 on 2024-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0004_alter_photo_rememberdate_alter_photo_rememberphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembertree',
            name='flowerType',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
