# Generated by Django 5.0.7 on 2024-07-22 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0005_alter_remembertree_flowertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('rememberTree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rememberTree.remembertree')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('date_answered', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answers', to='rememberTree.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date_answered')},
            },
        ),
    ]
