# Generated by Django 5.0.7 on 2024-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0006_question_userquestionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rememberTree',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('DENIAL', 'Denial'), ('ANGER', 'Anger'), ('BARGAINING', 'Bargaining'), ('DEPRESSION', 'Depression'), ('ACCEPTANCE', 'Acceptance')], default='', max_length=20),
        ),
    ]
