# Generated by Django 5.0.7 on 2024-07-24 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorialHall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorialhall",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
