# Generated by Django 5.0.7 on 2024-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorialHall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialhall',
            name='info',
            field=models.CharField(max_length=70, verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='wreath',
            name='comment',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='헌화 한마디'),
        ),
    ]
