# Generated by Django 5.0.7 on 2024-07-24 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorialHall", "0003_alter_memorialhall_participation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorialhall",
            name="token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
