# Generated by Django 5.0.7 on 2024-07-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorialHall", "0004_alter_memorialhall_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorialhall",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="get_thumbnail_upload_path",
                verbose_name="대표사진",
            ),
        ),
    ]
