# Generated by Django 5.0.7 on 2024-07-29 02:25

import memorialHall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorialHall', '0005_alter_memorialhall_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialhall',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=memorialHall.models.get_thumbnail_upload_path, verbose_name='대표사진'),
        ),
    ]
