# Generated by Django 5.0.7 on 2024-07-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorialHall', '0006_alter_memorialhall_thumbnail'),
        ('memorialHall', '0006_wreath_commemorate_wreath_sad_wreath_sympathize_and_more'),
    ]

    operations = [
    ]
