# Generated by Django 5.0.7 on 2024-07-29 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorialHall", "0007_merge_20240729_1347"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="commemorate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="com_msg",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sad",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sad_msg",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sympathize",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sym_msg",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="todak",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="todak_mse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="together",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="together_msg",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wreath",
            name="commemorate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="com_wreath",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wreath",
            name="sad",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sad_wreath",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wreath",
            name="sympathize",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sym_wreath",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wreath",
            name="todak",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="todak_wreath",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wreath",
            name="together",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="together_wreath",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
